fix logging error once and for all
Signed-off-by: JohnFawkes <33303104+JohnFawkes@users.noreply.github.com>

diff --git a/system/xbin/dns_switch b/system/xbin/dns_switch
--- a/system/xbin/dns_switch
+++ b/system/xbin/dns_switch
@@ -1,14 +1,16 @@
-#!/system/bin/sh
+
 # Terminal Magisk Mod Template
 # by veez21 @ xda-developers
 # Modified by @JohnFawkes - Telegram
 # Supersu/all-root compatibility with Unity and @Zackptg5
 # Variables
 
-. $MODULEROOT/$MODID/logging.sh || exit $?
+log_start "Running Log script." >> $LOG 2>&1
+
+. $MODPATH/logging.sh || exit $?
 
 OLDPATH=$PATH
-#CACHELOC=<CACHELOC>
+CACHELOC=<CACHELOC>
 SDCARD=/storage/emulated/0
 TMPLOG=DNSSwitch_logs.log
 TMPLOGLOC=$CACHELOC/DNSSwitch_logs
@@ -20,13 +22,13 @@ quit() {
   exit $?
 }
 
-#MODPROP=<MODPROP>
-$MAGISK && [ ! -f $MODPROP ]
-[ -f $MODPROP ] || { echo "Module not detected!"; quit 1; }
-
 # Detect root
 _name=$(basename $0)
-ls /data >/dev/null 2>&1 || { echo "$MODID needs to run as root!"; echo "type 'su' then '$_name'"; quit 1; }
+ls /data >/dev/null 2>&1 || { echo "$ID needs to run as root!"; echo "type 'su' then '$_name'"; exit 1; }
+
+MODPROP=<MODPROP>
+$MAGISK && [ ! -f $MODPROP ]
+[ -f $MODPROP ] || { echo "Module not detected!"; quit 1; }
 
 # Set Log Files
 mount -o remount,rw $CACHELOC 2>/dev/null
@@ -56,8 +58,6 @@ $CACHELOC/DNSSwitch-old.log
 $CACHELOC/DNSSwitch-verbose.log
 $CACHELOC/DNSSwitch-verbose-old.log
 "
-
-
 
 #ZACKPTG5 BUSYBOX
 #=========================== Set Busybox up
@@ -115,15 +115,6 @@ else
 fi
 
 # Functions
-grep_prop() {
-  REGEX="s/^$1=//p"
-  shift
-  FILES=$@
-  [ -z "$FILES" ] && FILES='/system/build.prop'
-  sed -n "$REGEX" $FILES 2>/dev/null | head -n 1
-}
-
-
 api_level_arch_detect() {
   API=`grep_prop ro.build.version.sdk`
   ABI=`grep_prop ro.product.cpu.abi | cut -c-3`
@@ -144,6 +135,37 @@ set_perm() {
   [ -z $5 ] && chcon 'u:object_r:system_file:s0' $1 || chcon $5 $1 || return 1
 }
 
+set_perm_recursive() {
+  find $1 -type d 2>/dev/null | while read dir; do
+    set_perm $dir $2 $3 $4 $6
+  done
+  find $1 -type f -o -type l 2>/dev/null | while read file; do
+    set_perm $file $2 $3 $5 $6
+  done
+}
+
+# Mktouch
+mktouch() {
+  mkdir -p ${1%/*} 2>/dev/null
+  [ -z $2 ] && touch $1 || echo $2 > $1
+  chmod 644 $1
+}
+
+# Grep prop
+grep_prop() {
+  local REGEX="s/^$1=//p"
+  shift
+  local FILES=$@
+  [ -z "$FILES" ] && FILES='/system/build.prop'
+  sed -n "$REGEX" $FILES 2>/dev/null | head -n 1
+}
+
+# Abort
+abort() {
+  echo "$1"
+  exit 1
+}
+
 magisk_version() {
   if grep MAGISK_VER /data/adb/magisk/util_functions.sh; then
 		log_print "$MAGISK_VERSION $MAGISK_VERSIONCODE" >> $LOG 2>&1
@@ -160,13 +182,13 @@ DEVICE=$(getprop ro.product.device)
 ROM=$(getprop ro.build.display.id)
 api_level_arch_detect
 # Version Number
-VER=$(grep_prop version $MODPROP)
+VER=$(echo $(get_file_value version $MODPROP "version=") | sed 's|-.*||')
 # Version Code
-REL=$(grep_prop versionCode $MODPROP)
+REL=$(echo $(get_file_value versionCode $MODPROP "versionCode=") | sed 's|-.*||')
 # Author
-AUTHOR=$(grep_prop author $MODPROP)
+AUTHOR=$(echo $(get_file_value author $MODPROP "author=") | sed 's|-.*||')
 # Mod Name/Title
-MODTITLE=$(grep_prop name $MODPROP)
+MODTITLE=$(echo $(get_file_value $MODPROP "name=") | sed 's|-.*||')
 #Grab Magisk Version
 MAGISK_VERSION=$(echo $(get_file_value /data/adb/magisk/util_functions.sh "MAGISK_VER=") | sed 's|-.*||')
 MAGISK_VERSIONCODE=$(echo $(get_file_value /data/adb/magisk/util_functions.sh "MAGISK_VER_CODE=") | sed 's|-.*||')
@@ -186,24 +208,28 @@ loadBar=' '			# Load UI
 # Remove color codes if -nc or in ADB Shell
 [ -n "$1" -a "$1" == "-nc" ] && shift && NC=true
 [ "$NC" -o -n "$LOGNAME" ] && {
-	G=''; R=''; Y=''; B=''; V=''; Bl=''; C=''; W=''; N=''; BGBL=''; loadBar='=';
+  G=''; R=''; Y=''; B=''; V=''; Bl=''; C=''; W=''; N=''; BGBL=''; loadBar='=';
 }
 
-# Divider (based on $MODTITLE, $VER, and $REL characters)
-character_no=$(echo "$MODTITLE $VER $REL" | tr " " '_' | wc -c)
+# No. of characters in $MODTITLE, $VER, and $REL
+character_no=$(echo "$MODTITLE $VER $REL" | wc -c)
+
+# Divider
 div="${Bl}$(printf '%*s' "${character_no}" '' | tr " " "=")${N}"
 
-# Title Div
+# title_div [-c] <title>
+# based on $div with <title>
 title_div() {
-  no=$(echo "$@" | wc -c)
-  extdiv=$((no-character_no))
-  echo "${W}$@${N} ${Bl}$(printf '%*s' "$extdiv" '' | tr " " "=")${N}"
+  [ "$1" == "-c" ] && local character_no=$2 && shift 2
+  [ -z "$1" ] && { local message=; no=0; } || { local message="$@ "; local no=$(echo "$@" | wc -c); }
+  [ $character_no -gt $no ] && local extdiv=$((character_no-no)) || { echo "Invalid!"; return; }
+  echo "${W}$message${N}${Bl}$(printf '%*s' "$extdiv" '' | tr " " "=")${N}"
 }
 
 # set_file_prop <property> <value> <prop.file>
 set_file_prop() {
   if [ -f "$3" ]; then
-    if grep "$1=" "$3"; then
+    if grep -q "$1=" "$3"; then
       sed -i "s/${1}=.*/${1}=${2}/g" "$3"
     else
       echo "$1=$2" >> "$3"
@@ -219,7 +245,7 @@ ProgressBar() {
 # Determine Screen Size
   if [[ "$COLUMNS" -le "57" ]]; then
     local var1=2
-	local var2=20
+	  local var2=20
   else
     local var1=4
     local var2=40
@@ -307,10 +333,10 @@ prandom() {
 # Print Center
 # Prints text in the center of terminal
 pcenter() {
-  local CHAR=$(echo $@ | sed 's|\e[[0-9;]*m||g' | wc -m)
+  local CHAR=$(printf "$@" | sed 's|\\e[[0-9;]*m||g' | wc -m)
   local hfCOLUMN=$((COLUMNS/2))
   local hfCHAR=$((CHAR/2))
-  local indent=$((hfCOLUMN-hfCHAR-1))
+  local indent=$((hfCOLUMN-hfCHAR))
   echo "$(printf '%*s' "${indent}" '') $@"
 }
 
@@ -361,108 +387,6 @@ get_first() {
 		;;
 	esac
 }
-
-set_perm() {
-  chown $2:$3 $1 || return 1
-  chmod $4 $1 || return 1
-  [ -z $5 ] && chcon 'u:object_r:system_file:s0' $1 || chcon $5 $1 || return 1
-}
-
-#Log Functions
-# Saves the previous log (if available) and creates a new one
-#log_start() {
-#if [ -f "$LOG" ]; then
-#	mv -f $LOG $oldLOG
-#fi
-#touch $LOG
-#echo " " >> $LOG 2>&1
-#echo "    *********************************************" >> $LOG 2>&1
-#echo "    *              DNSSwitch                    *" >> $LOG 2>&1
-#echo "    *********************************************" >> $LOG 2>&1
-#echo "    *                 $VER                      *" >> $LOG 2>&1
-#echo "    *********************************************" >> $LOG 2>&1
-#echo "    *              John Fawkes                  *" >> $LOG 2>&1
-#echo "    *********************************************" >> $LOG 2>&1
-#echo " " >> $LOG 2>&1
-#log_script_chk "Log start."
-#}
-
-#collect_logs() {
-#	log_handler "Collecting logs and information."
-	# Create temporary directory
-#	mkdir -pv $TMPLOGLOC >> $LOG 2>&1
-
-	# Saving Magisk and module log files and device original build.prop
-#	for ITEM in $LOGGERS; do
-#		if [ -f "$ITEM" ]; then
-#			case "$ITEM" in
-#				*build.prop*)	BPNAME="build_$(echo $ITEM | sed 's|\/build.prop||' | sed 's|.*\/||g').prop"
-#				;;
-#				*)	BPNAME=""
-#				;;
-#			esac
-#			cp -af $ITEM ${TMPLOGLOC}/${BPNAME} >> $LOG 2>&1
-#		else
-#			case "$ITEM" in
-#				*/cache)
-#					if [ "$CACHELOC" == "/cache" ]; then
-#						CACHELOCTMP=/cache
-#					else
-#						CACHELOCTMP=/data/cache
-#					fi
-#					ITEMTPM=$(echo $ITEM | sed 's|$CACHELOC|$CACHELOCTMP|')
-#					if [ -f "$ITEMTPM" ]; then
-#						cp -af $ITEMTPM $TMPLOGLOC >> $LOG 2>&1
-#					else
-#						log_handler "$ITEM not available."
-#					fi
-#        ;;
-#				*)	log_handler "$ITEM not available."
-#				;;
-#			esac
-#    fi
-#	done
-
-# Saving the current prop values
-#if $MAGISK; then
-#  log_handler "RESETPROPS"
-#  echo "==========================================" >> $LOG 2>&1
-#	resetprop >> $LOG 2>&1
-#else
-#  log_handler "GETPROPS"
-#  echo "==========================================" >> $LOG 2>&1
-#	getprop >> $LOG 2>&1
-#fi
-#if $MAGISK; then
-#  log_print " Collecting Modules Installed "
-#  echo "==========================================" >> $LOG 2>&1
-#  ls $MOUNTPATH >> $INSTLOG 2>&1
-#  log_print " Collecting Logs for Installed Files "
-#  echo "==========================================" >> $LOG 2>&1
-#  log_handler "$(du -ah $MODPATH)" >> $LOG 2>&1
-#fi
-
-# Package the files
-#cd $CACHELOC
-#tar -zcvf DNSSwitch_logs.tar.xz DNSSwitch_logs >> $LOG 2>&1
-
-# Copy package to internal storage
-#mv -f $CACHELOC/DNSSwitch_logs.tar.xz $SDCARD >> $LOG 2>&1
-
-#if  [ -e $SDCARD/DNSSwitch_logs.tar.xz ]; then
-#  log_print "DNSSwitch_logs.tar.xz Created Successfully."
-#else
-#  log_print "Archive File Not Created. Error in Script. Please contact @JohnFawkes on Telegram"
-#fi
-
-# Remove temporary directory
-#rm -rf $TMPLOGLOC >> $LOG 2>&1
-
-#log_handler "Logs and information collected."
-#}
-
-# Load functions
-#log_start "Running Log script." >> $LOG 2>&1
 
 help_me() {
   cat << EOF
